/*
 * WbyWxInfo.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.io.File;

import javax.swing.ImageIcon;

import org.json.JSONException;

import spider.WbySpider;

/**
 *
 * @author  __USER__
 */
public class WbyWxInfo extends javax.swing.JFrame {

	/** Creates new form WbyWxInfo */
	public WbyWxInfo() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		et_code = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		btn_code = new javax.swing.JButton();
		btn_start = new javax.swing.JButton();
		et_page = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		lb_result = new javax.swing.JLabel();
		lb_code = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		et_code.setColumns(6);

		jLabel1.setText("\u9a8c\u8bc1\u7801:");

		btn_code.setText("\u83b7\u53d6\u9a8c\u8bc1\u7801");
		btn_code.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_codeMouseClicked(evt);
			}
		});

		btn_start.setText("\u5f00\u59cb");
		btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_startMouseClicked(evt);
			}
		});

		et_page.setColumns(5);

		jLabel2.setText("\u8d77\u59cb\u9875:");

		lb_result.setText("  ");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lb_result)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												et_code,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jLabel2))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												btn_code)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												btn_start)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								lb_code)
																						.addComponent(
																								et_page,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																et_code,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																et_page,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(20, 20, 20)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btn_code)
														.addComponent(btn_start)
														.addComponent(lb_code))
										.addGap(18, 18, 18)
										.addComponent(lb_result)
										.addContainerGap(30, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {

		new Thread(new Runnable() {

			@Override
			public void run() {
				String code = et_code.getText();
//				String page = et_page.getText();
				if (WbySpider.login(code)) {
					try {
						WbySpider.startGetWX();
					} catch (JSONException e) {
						e.printStackTrace();
					}
				}
			}
		}).start();
	}

	private void btn_codeMouseClicked(java.awt.event.MouseEvent evt) {

		new Thread(new Runnable() {

			@Override
			public void run() {
				File file;
				try {
					file = WbySpider.getCode();
					lb_code.setIcon(new ImageIcon(file.getAbsolutePath()));
				} catch (Exception e) {
					lb_result.setText("我曹，获取验证码报错了");
				}
			}
		}).start();

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WbyWxInfo().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_code;
	private javax.swing.JButton btn_start;
	private javax.swing.JTextField et_code;
	private javax.swing.JTextField et_page;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel lb_code;
	private javax.swing.JLabel lb_result;
	// End of variables declaration//GEN-END:variables

}